modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="hormone"
version="1.0.2"
displayName="Hormone"
credits="MCreator for the awsome tool, and alex for the idea"
displayURL="https://github.com/TIBTHINK/hormone"
authors="tibthink"
description='''
Adds hormones into the game we all love
'''

[[dependencies.hormone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




